resources:
- https://github.com/opensourceways/app-bot/deploy?ref=master
commonLabels:
  app: openeuler-bot-debug
nameSuffix: -debug
namespace: bot-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- configmap.yaml
- deployment.yaml
- secrets.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/ci-bot
  newTag: 00820f180237af425c62da0cbf988fe70106b471.1627289553
